name: Deploy to AWS ECS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Build and Deploy Medusa to ECS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      ECS_CLUSTER: Medusa-Cluster
      ECS_SERVICE: medusa-service
      ECS_TASK_DEFINITION: medusa-task
      CONTAINER_NAME: medusa-container

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pull Docker Image
      run: docker pull pranjul1/medusa-backend:latest

    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ env.ECS_CLUSTER }}
        service: ${{ env.ECS_SERVICE }}
        task-definition: ecs-task-definition.json
